### ISSUE TITLE
Error: Recursive variable definition

### ISSUE THREAD

**Issue by speaud** [3nvi/webpack2-semantic-ui-theming#1]
After clone && npm i run build cmd and the following error is thrown

`      [46] ./~/css-loader!./~/less-loader/dist/cjs.js!./~/semantic-ui-less/semantic.less 260 bytes {0} [built] [failed] [1 error]
      [47] ./~/less-loader/dist/stringifyLoader.js!./my-semantic-theme/site/elements/button.variables 109 bytes [built]
        + 79 hidden modules

    ERROR in ./~/css-loader!./~/less-loader/dist/cjs.js!./~/semantic-ui-less/semantic.less
    Module build failed:

    @theme: @@element;
          ^
    Recursive variable definition for @placeholder
          in /Users/joshuamummert/Webapps/demo-apps/webpack2-semantic-ui-theming/node_modules/semantic-ui-less/theme.less (line 9, column 8)`

**Comment by 3nvi** [comment]
Hey, you are right, there were some updates on packages that broke the build. I'll take a loot at it today and hopefully fix it by the end of the day.

Thanks for reporting!

**Comment by 3nvi** [comment]
Resolved through 69d04784619567d34318d6f8900a095098a3a4a2
